apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dvdrental
  name: dvdrental
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvdrental
  template:
    metadata:
      labels:
        app: dvdrental
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
      containers:
        - name: dvdrental
          image: quay.io/ssorj/dvdrental
          ports:
            - containerPort: 5432
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
